# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CSTC-iOS-Survey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CSTC-iOS-Survey
  pod 'Mapbox-iOS-SDK', '~> 5.9.0'

  target 'CSTC-iOS-SurveyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
